version: '3.9'

services:

  client:
    build:
      context: ./client/
    image: client
    restart: always
    env_file:
      - ./.env
    ports:
      - "8083:80"
    depends_on:
      - server

  server:
    build:
      context: ./server/
    image: server
    restart: always
    env_file:
      - ./.env
    ports:
      - "8082:4332"
    depends_on:
      - mongo


  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - "8081:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}