version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - "8081:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}